<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HUYF9-PF1L46YU" name="timeout.TestTimeOut" tests="2" failures="0" timestamp="16 一月 2020 02:44:17 GMT" time="0.591" errors="2">
  <testcase name="test1" time="0.349" classname="timeout.TestTimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method timeout.TestTimeOut.test1() didn&#039;t finish within the time-out 240">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method timeout.TestTimeOut.test1() didn't finish within the time-out 240
at java.lang.Throwable.printStackTrace(Throwable.java:643)
at java.lang.Throwable.printStackTrace(Throwable.java:634)
at timeout.TestTimeOut.test1(TestTimeOut.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.242" classname="timeout.TestTimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method timeout.TestTimeOut.test2() didn&#039;t finish within the time-out 240">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method timeout.TestTimeOut.test2() didn't finish within the time-out 240
at java.lang.Thread.sleep(Native Method)
at timeout.TestTimeOut.test2(TestTimeOut.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- test2 -->
</testsuite> <!-- timeout.TestTimeOut -->
